import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const IloomChair1 = (props) => {
  const { nodes, materials } = useGLTF("/iloom/IloomChair1/3DObject.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#0"].geometry}
        material={materials.material_08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#1"].geometry}
        material={materials.material_08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#2"].geometry}
        material={materials.material_04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#3"].geometry}
        material={materials.material_04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#4"].geometry}
        material={materials.material_04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#5"].geometry}
        material={materials.material_05}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#6"].geometry}
        material={materials.material_08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#7"].geometry}
        material={materials.material_08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#8"].geometry}
        material={materials.material_07}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#9"].geometry}
        material={materials.material_09}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#10"].geometry}
        material={materials.material_08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#11"].geometry}
        material={materials.material_09}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#12"].geometry}
        material={materials.material_04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#13"].geometry}
        material={materials.material_04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#14"].geometry}
        material={materials.material_08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#15"].geometry}
        material={materials.material_03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#16"].geometry}
        material={materials.material_08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#17"].geometry}
        material={materials.material_10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#18"].geometry}
        material={materials.material_04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#19"].geometry}
        material={materials.material_04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#20"].geometry}
        material={materials.material_01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#21"].geometry}
        material={materials.material_08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#22"].geometry}
        material={materials.material_04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#23"].geometry}
        material={materials.material_01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#24"].geometry}
        material={materials.material_01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#25"].geometry}
        material={materials.material_04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#26"].geometry}
        material={materials.material_03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#27"].geometry}
        material={materials.material_01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#28"].geometry}
        material={materials.material_03}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#29"].geometry}
        material={materials.material_01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["meshobj#30"].geometry}
        material={materials.material_04}
      />
    </group>
  );
};
useGLTF.preload("/iloom/IloomChair1/3DObject.glb");

export default IloomChair1;
